packages/libflac: don't hardcode altivec options in CPUCFLAGS
The '-maltivec' and '-mabi=altivec' options always
included in the CPUCPFLAGS variable, even if altivec
support is disabled. This causes build failure on
powerpc platforms without altivec support:

  bitmath.c:1:0: error: AltiVec and E500 instructions cannot coexist

Update the src/libFLAC/Makefile.am template to skip
altivec options if 'FLaC__USE_ALTIVEC' is not used.

Signed-off-by: Gabor Juhos <juhosg@openwrt.org>

SVN-Revision: 39443